/**
 * Menu data — לחיים בכריתים
 */
const TRANSLATIONS = {
  he: {
    restaurantName: 'לחיים בכריתים',
    pageTitle: 'מסעדת לחיים | מסעדה כשרה למהדרין בכרתים',
    pageDescription: 'תפריט דיגיטלי — לחיים בכריתים, כרתים.',
    bh: 'ב״ה',
    myCart: 'הסל שלי',
    myOrderView: 'ההזמנה שלי',
    takeawayLockedToast: 'יש לכם הזמנה פתוחה — אפשר להוסיף פריטים לאותה הזמנה בלבד',
    takeawayLockedAction: 'הזמנה פתוחה — הוסיפו פריטים לאותה הזמנה',
    tableLabel: 'שולחן',
    changeTableAria: 'שנה מספר שולחן',
    backToOrderType: 'חזרה',
    backToOrderTypeAria: 'חזרה לבחירת סוג הזמנה',
    viewMenu: 'צפייה בתפריט',
    heroWelcome: 'ברוכים הבאים',
    heroTitle: 'מסעדת לחיים בכרתים',
    heroKosher: 'כשר למהדרין',
    heroTagline: '',
    skipToMenu: 'דלג לתפריט',
    myOrder: 'ההזמנה שלי',
    cartEmpty: 'העגלה ריקה',
    total: 'סה״כ',
    currentTotal: 'סה״כ עגלה',
    clearCart: 'נקה עגלה',
    clearCartConfirm: 'למחוק את כל המוצרים מהעגלה?',
    sendOrder: 'שלח הזמנה',
    sendingOrder: 'שולח...',
    orderSentSuccess: 'ההזמנה נשלחה בהצלחה למטבח',
    orderSentFail: 'שליחת ההזמנה נכשלה\nנסה שוב',
    receiptTitle: 'ההזמנה נשלחה',
    receiptEyebrow: 'כרטיס הזמנה',
    receiptContinue: 'הוסף פריטים להזמנה קיימת',
    receiptNewOrder: 'הזמנה חדשה',
    receiptClose: 'סגור',
    orderingClosedBanner: 'ההזמנות פתוחות בין 14:00 ל־21:00. כרגע ניתן לצפות בתפריט בלבד.',
    orderingClosedToast: 'לא ניתן להזמין כרגע — ההזמנות פתוחות בין 14:00 ל־21:00',
    orderingClosedAction: 'לא ניתן להוסיף לעגלה כרגע',
    receiptTotal: 'סה״כ להזמנה זו',
    receiptTable: 'שולחן {n}',
    receiptTakeaway: 'איסוף עצמי',
    receiptOrderNo: 'מספר הזמנה',
    receiptRememberNo: 'שמרו את מספר ההזמנה — תצטרכו אותו באיסוף',
    receiptPickupAsap: 'איסוף: בהקדם',
    receiptPickupAt: 'איסוף: {time}',
    receiptEmpty: 'אין פריטים',
    requestBill: 'בקש חשבון',
    requestBillConfirm: 'האם ברצונך לבקש חשבון?',
    requestBillYes: 'כן',
    requestBillCancel: 'ביטול',
    requestBillSuccess: 'בקשת החשבון נשלחה למלצר',
    requestBillFail: 'לא ניתן לבקש חשבון',
    requestBillNoOrder: 'אין הזמנה פעילה לשולחן',
    couponAsk: 'יש לך קוד קופון?',
    couponApply: 'החל קופון',
    couponPlaceholder: 'קוד קופון',
    couponOk: 'קופון אומת בהצלחה\n{percent}% הנחה הוחלה על ההזמנה',
    couponFail: 'קוד קופון לא תקין',
    couponSubtotal: 'סה״כ לפני הנחה',
    couponDiscount: 'הנחת קופון ({percent}%)',
    couponPay: 'לתשלום',
    tableChangeLocked: 'לא ניתן להחליף שולחן לאחר שליחת הזמנה',
    clearCartYes: 'כן, רוקן',
    clearCartCancel: 'ביטול',
    addToCart: 'הוסף לסל',
    addedToCart: '{name} נוסף לסל',
    outOfStock: 'אזל מהמלאי',
    decrease: 'הפחת כמות',
    increase: 'הוסף כמות',
    close: 'סגור',
    openCart: 'פתח סל הזמנה',
    openMyOrder: 'פתח את ההזמנה שלי',
    openMenu: 'פתח תפריט',
    showDish: 'הצג פרטים על {name}',
    perUnit: '{price} ליחידה',
    currency: '€',
    langToggleAria: 'החלפת שפה – עברית / English',
    mainsNote: 'כל המנות העיקריות מוגשות עם תוספת אחת חמה (למעט שיפודי קבב ומוקפץ עוף).',
    mainsSidesTitle: 'תוספות לבחירה',
    mainsSidesList: "צ'יפס פריך | אורז לבן | שעועית ירוקה | פירה | ירקות בתנור",
    sidesIncluded: 'כלול',
    sidesIncludedNote: 'כלול במנה העיקרית',
    sideForMain: 'תוספת ל־{name}',
    servedWith: 'מוגש עם: {sides}',
    maxSidesPerMain: 'ניתן לבחור תוספת חמה אחת לכל מנה עיקרית',
    chooseMainFirst: 'יש לבחור מנה עיקרית לפני תוספת חמה',
    chooseSidesTitle: 'בחרו תוספת חמה',
    chooseSidesSubtitle: 'תוספת אחת למנה: {name}',
    sidesSelected: '{count} מתוך 1 נבחרו',
    sidesContinue: 'המשך',
    sideLabel: 'תוספת',
    contact: 'יצירת קשר',
    hours: 'שעות פעילות',
    hoursDays: 'א׳ – ה׳',
    address: 'כתובת',
    addressText: 'Analipsi 700 14, Greece',
    copyright: 'מסעדת לחיים בכרתים כשר למהדרין',
    footerTagline: 'The Pearl of Crete',
    followUs: 'עקבו אחרינו',
    categories: {
      starters: 'ראשונות ונשנושים',
      mains: 'מנות עיקריות',
      hotSides: 'תוספות חמות לבחירה',
      salads: 'סלטים',
      desserts: 'קינוחים',
      coldDrinks: 'שתייה קלה',
      hotDrinks: 'שתייה חמה',
    },
  },
  en: {
    restaurantName: 'LeChaim in Keri',
    pageTitle: 'Lechaim Restaurant | Mehadrin Kosher Restaurant in Crete',
    pageDescription: 'Digital menu — LeChaim in Keri, Crete.',
    bh: 'B"H',
    myCart: 'My Cart',
    myOrderView: 'My order',
    takeawayLockedToast: 'You have an open order — you can only add items to that order',
    takeawayLockedAction: 'Open order — add items to the same order',
    tableLabel: 'Table',
    changeTableAria: 'Change table number',
    backToOrderType: 'Back',
    backToOrderTypeAria: 'Back to order type selection',
    viewMenu: 'View Menu',
    heroWelcome: 'Welcome',
    heroTitle: 'Lechaim Restaurant in Crete',
    heroKosher: 'Mehadrin Kosher',
    heroTagline: '',
    skipToMenu: 'Skip to menu',
    myOrder: 'My Order',
    cartEmpty: 'Cart is empty',
    total: 'Total',
    currentTotal: 'Cart total',
    clearCart: 'Clear cart',
    clearCartConfirm: 'Remove all items from the cart?',
    sendOrder: 'Send order',
    sendingOrder: 'Sending...',
    orderSentSuccess: 'Order sent successfully to the kitchen',
    orderSentFail: 'Failed to send order\nTry again',
    receiptTitle: 'Order sent',
    receiptEyebrow: 'Order card',
    receiptContinue: 'Add items to existing order',
    receiptNewOrder: 'New order',
    receiptClose: 'Close',
    orderingClosedBanner: 'Ordering is open 14:00–21:00. You can browse the menu only right now.',
    orderingClosedToast: 'Ordering is closed — open daily 14:00–21:00',
    orderingClosedAction: 'Ordering is unavailable right now',
    receiptTotal: 'Total for this order',
    receiptTable: 'Table {n}',
    receiptTakeaway: 'Takeaway',
    receiptOrderNo: 'Order number',
    receiptRememberNo: 'Remember this order number — you will need it at pickup',
    receiptPickupAsap: 'Pickup: ASAP',
    receiptPickupAt: 'Pickup: {time}',
    receiptEmpty: 'No items',
    requestBill: 'Request bill',
    requestBillConfirm: 'Would you like to request the bill?',
    requestBillYes: 'Yes',
    requestBillCancel: 'Cancel',
    requestBillSuccess: 'Bill request sent to the waiter',
    requestBillFail: 'Could not request the bill',
    requestBillNoOrder: 'No active order for this table',
    couponAsk: 'Have a coupon code?',
    couponApply: 'Apply coupon',
    couponPlaceholder: 'Coupon code',
    couponOk: 'Coupon verified\n{percent}% discount applied',
    couponFail: 'Invalid coupon code',
    couponSubtotal: 'Subtotal',
    couponDiscount: 'Coupon discount ({percent}%)',
    couponPay: 'Amount due',
    tableChangeLocked: 'Table cannot be changed after an order is sent',
    clearCartYes: 'Yes, clear',
    clearCartCancel: 'Cancel',
    addToCart: 'Add to cart',
    addedToCart: '{name} added to cart',
    outOfStock: 'Out of stock',
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
    close: 'Close',
    openCart: 'Open order cart',
    openMyOrder: 'Open my order',
    openMenu: 'Open menu',
    showDish: 'View details for {name}',
    perUnit: '{price} each',
    currency: '€',
    langToggleAria: 'Switch language – Hebrew / English',
    mainsNote: 'All main courses are served with one hot side (except kebab skewers and stir-fried chicken).',
    mainsSidesTitle: 'Sides to choose from',
    mainsSidesList: 'Crispy fries | White rice | Green beans | Mashed potatoes | Oven vegetables',
    sidesIncluded: 'Included',
    sidesIncludedNote: 'Included with the main course',
    sideForMain: 'Side for {name}',
    servedWith: 'Served with: {sides}',
    maxSidesPerMain: 'One hot side per main course',
    chooseMainFirst: 'Choose a main course before adding a hot side',
    chooseSidesTitle: 'Choose a hot side',
    chooseSidesSubtitle: 'One side for: {name}',
    sidesSelected: '{count} of 1 selected',
    sidesContinue: 'Continue',
    sideLabel: 'Side',
    contact: 'Contact',
    hours: 'Opening Hours',
    hoursDays: 'Sun – Thu',
    address: 'Address',
    addressText: 'Analipsi 700 14, Greece',
    copyright: 'Lechaim Restaurant in Crete — Mehadrin Kosher',
    footerTagline: 'The Pearl of Crete',
    followUs: 'Follow us',
    categories: {
      starters: 'Starters & Snacks',
      mains: 'Main Courses',
      hotSides: 'Hot Sides to Choose',
      salads: 'Salads',
      desserts: 'Desserts',
      coldDrinks: 'Soft Drinks',
      hotDrinks: 'Hot Drinks',
    },
  },
  el: {
    currentTotal: 'Τρέχον Σύνολο',
    requestBill: 'Λογαριασμός',
    requestBillConfirm: 'Θέλετε να ζητήσετε τον λογαριασμό;',
    requestBillYes: 'Ναι',
    requestBillCancel: 'Ακύρωση',
    requestBillSuccess: 'Το αίτημα λογαριασμού στάλθηκε στον σερβιτόρο',
    requestBillFail: 'Δεν ήταν δυνατή η αίτηση λογαριασμού',
    requestBillNoOrder: 'Δεν υπάρχει ενεργή παραγγελία',
    tableChangeLocked: 'Δεν μπορείτε να αλλάξετε τραπέζι μετά την αποστολή παραγγελίας',
    clearCartYes: 'Ναι, άδειασμα',
    clearCartCancel: 'Ακύρωση',
  },
};

const DISH_I18N = {
  en: {
    'salad-plate': {
      name: 'Opening Salad Platter',
      desc: 'Selection of refreshing house salads with warm pitas (recommended for the table center).',
    },
    hummus: {
      name: 'House Hummus',
      desc: 'Creamy handmade hummus, served with olive oil, cumin and pitas.',
    },
    'hummus-egg': {
      name: 'Hummus with Egg',
      desc: 'Creamy handmade hummus, served with olive oil, cumin and pitas, topped with egg.',
    },
    'hummus-meat': {
      name: 'Hummus with Meat',
      desc: 'Creamy handmade hummus, served with olive oil, cumin and pitas, topped with meat.',
    },
    mushrooms: {
      name: 'Hot Mushrooms',
      desc: 'Fresh mushrooms sautéed in garlic, olive oil and parsley.',
    },
    'fries-classic': {
      name: 'Classic Fries',
      desc: 'Crispy potato fries.',
    },
    schnitzel: {
      name: "Chef's Schnitzel",
      desc: 'Crispy chicken breast in golden breadcrumb coating.',
    },
    'chicken-steak': {
      name: 'Grilled Chicken Steak',
      desc: 'Juicy chicken cut with Mediterranean seasoning.',
    },
    'whole-fish': {
      name: 'Whole Baked Sea Bream',
      desc: 'Fresh sea bream baked with herbs and olive oil.',
    },
    'denis-fillet': {
      name: 'Oven-Baked Sea Bream Fillet',
      desc: 'Sea bream fillet baked with green herbs and olive oil.',
    },
    salmon: {
      name: 'Oven-Baked Salmon',
      desc: 'Salmon fillet baked with delicate seasoning.',
    },
    kebab: {
      name: 'Kebab Skewers',
      desc: 'Served with tahini and a small side salad.',
    },
    'chicken-stirfry': {
      name: 'Stir-Fried Chicken',
      desc: 'Chicken pieces stir-fried with vegetables in soy and ginger sauce.',
    },
    'chicken-salad': {
      name: 'Rich Chicken Salad',
      desc: 'Warm chicken on lettuce with seasonal vegetables and vinaigrette.',
    },
    'israeli-salad': {
      name: 'Israeli Chopped Salad',
      desc: 'Fresh chopped vegetable salad with herbs.',
    },
    'green-salad': {
      name: 'Green Salad',
      desc: 'Selection of fresh leaves with vinaigrette.',
    },
    'market-salad': {
      name: 'Market Salad',
      desc: 'Fresh seasonal vegetables.',
    },
    'fruit-plate': {
      name: 'Seasonal Fruit Platter',
      desc: 'Selection of fresh, refreshing cut fruits.',
    },
    coke: { name: 'Coca-Cola', desc: '' },
    'coke-zero': { name: 'Coke Zero', desc: '' },
    fanta: { name: 'Fanta', desc: '' },
    sprite: { name: 'Sprite', desc: '' },
    'red-bull': { name: 'Red Bull', desc: '' },
    heineken: { name: 'Heineken', desc: '' },
    corona: { name: 'Corona', desc: '' },
    soda: { name: 'Soda', desc: '' },
    water: { name: 'Mineral Water', desc: '' },
    'fruit-shake': {
      name: 'Refreshing Fruit Shake',
      desc: 'Water / orange / soda base (depending on available fruits).',
    },
    espresso: {
      name: 'Espresso',
      desc: '',
    },
    hafukh: {
      name: 'Hafukh (soy milk available)',
      desc: '',
    },
    'black-coffee': { name: 'Black Coffee', desc: '' },
    'mint-tea': { name: 'Hot Mint Tea', desc: '' },
    puree: { name: 'Mashed Potatoes', desc: '' },
    rice: { name: 'White Rice', desc: '' },
    'oven-vegetables': { name: 'Oven Vegetables', desc: '' },
    'green-beans': { name: 'Green Beans', desc: '' },
    'fries-side': { name: 'Crispy Fries', desc: '' },
  },
};

function dishImage(id) {
  return `assets/images/dishes/${id}.webp`;
}

const MENU_DATA = {
  restaurant: 'לחיים בכריתים',
  categories: [
    {
      id: 'starters',
      titleKey: 'categories.starters',
      items: [
        {
          id: 'salad-plate',
          name: 'פלטת סלטים פתיחה',
          printName: 'Paletet Salatim',
          description: 'מבחר סלטי הבית המרעננים לצד פיתות חמות (מומלץ למרכז שולחן).',
          price: 15,
          image: dishImage('salad-plate'),
        },
        {
          id: 'hummus',
          name: 'חומוס הבית',
          printName: 'Hummus',
          description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ופיתות.',
          price: 15,
          image: dishImage('hummus'),
        },
        {
          id: 'hummus-egg',
          name: 'חומוס עם ביצה',
          printName: 'Hummus Im Beitza',
          description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ופיתות בתוספת ביצה.',
          price: 17,
          image: dishImage('hummus-egg'),
        },
        {
          id: 'hummus-meat',
          name: 'חומוס בשר',
          printName: 'Hummus Basar',
          description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ופיתות בתוספת בשר.',
          price: 19,
          image: dishImage('hummus-meat'),
        },
        {
          id: 'mushrooms',
          name: 'פטריות חמות',
          printName: 'Pitriyot Hamot',
          description: 'פטריות טריות מוקפצות בשום, שמן זית ופטרוזיליה.',
          price: 10,
          image: dishImage('mushrooms'),
        },
        {
          id: 'fries-classic',
          name: "צ'יפס קלאסי",
          printName: 'Chips',
          description: 'מנת תפוחי אדמה פריכים.',
          price: 10,
          image: dishImage('fries'),
        },
      ],
    },
    {
      id: 'mains',
      titleKey: 'categories.mains',
      descriptionKey: 'mainsNote',
      sidesTitleKey: 'mainsSidesTitle',
      sidesListKey: 'mainsSidesList',
      items: [
        {
          id: 'schnitzel',
          name: 'שניצל של השף',
          printName: 'Shnitzel',
          description: 'חזה עוף פריך בציפוי פירורי לחם מוזהבים.',
          price: 25,
          image: dishImage('schnitzel'),
        },
        {
          id: 'chicken-steak',
          name: 'סטייק פרגית בגריל',
          printName: 'Steak Pargit',
          description: 'נתח פרגית עסיסי בתיבול ים־תיכוני.',
          price: 26,
          image: dishImage('chicken-steak'),
        },
        {
          id: 'whole-fish',
          name: 'דג שלם בתנור',
          printName: 'Dag Shalem',
          description: 'דניס טרי אפוי עם עשבי תיבול ושמן זית.',
          price: 29,
          image: dishImage('denis'),
        },
        {
          id: 'denis-fillet',
          name: 'פילה דניס בתנור',
          printName: 'File Denis',
          description: 'פילה דניס בתנור בעשבי תיבול ירוקים ושמן זית.',
          price: 29,
          image: dishImage('denis-fillet'),
        },
        {
          id: 'salmon',
          name: 'נתח סלמון בתנור',
          printName: 'Salmon',
          description: 'פילה סלמון אפוי בתיבול עדין.',
          price: 29,
          image: dishImage('salmon'),
        },
        {
          id: 'kebab',
          name: 'שיפודי קבב',
          printName: 'Shpudei Kabab',
          description: 'מוגש לצד טחינה וסלטון קטן.',
          price: 27,
          image: dishImage('kebab'),
        },
        {
          id: 'chicken-stirfry',
          name: 'מוקפץ עוף',
          printName: 'Mukpatz Of',
          description: 'נתחי עוף מוקפצים עם ירקות ברוטב סויה וג\'ינג\'ר.',
          price: 20,
          image: dishImage('chicken-stirfry'),
        },
      ],
    },
    {
      id: 'salads',
      titleKey: 'categories.salads',
      items: [
        {
          id: 'chicken-salad',
          name: 'סלט פרגית עשיר',
          printName: 'Salat Pargit',
          description: 'נתחי פרגית חמים על מצע חסות, ירקות העונה ורוטב ויניגרט.',
          price: 18,
          image: dishImage('chicken-salad'),
        },
        {
          id: 'israeli-salad',
          name: 'סלט קצוץ ישראלי',
          printName: 'Salat Israeli',
          description: 'סלט ירקות קצוץ טרי עם עשבי תיבול.',
          price: 10,
          image: dishImage('israeli-salad'),
        },
        {
          id: 'green-salad',
          name: 'סלט ירוק',
          printName: 'Salat Yarok',
          description: 'מבחר עלים טריים עם רוטב ויניגרט.',
          price: 9,
          image: dishImage('green-salad'),
        },
        {
          id: 'market-salad',
          name: 'סלט שוק',
          printName: 'Salat Shuk',
          description: 'ירקות העונה טריים.',
          price: 9,
          image: dishImage('market-salad'),
        },
      ],
    },
    {
      id: 'desserts',
      titleKey: 'categories.desserts',
      items: [
        {
          id: 'fruit-plate',
          name: 'פלטת פירות העונה',
          printName: 'Paletet Perot',
          description: 'מבחר פירות טריים, מרעננים וחתוכים.',
          price: 18,
          image: dishImage('fruit-plate'),
        },
      ],
    },
    {
      id: 'coldDrinks',
      titleKey: 'categories.coldDrinks',
      items: [
        { id: 'coke', name: 'קוקה קולה', printName: 'Coca Cola', description: '', price: 3, image: dishImage('coke') },
        { id: 'coke-zero', name: 'קולה זירו', printName: 'Cola Zero', description: '', price: 3, image: dishImage('coke-zero') },
        { id: 'fanta', name: 'פאנטה', printName: 'Fanta', description: '', price: 3, image: dishImage('fanta') },
        { id: 'sprite', name: 'ספרייט', printName: 'Sprite', description: '', price: 3, image: dishImage('sprite') },
        { id: 'red-bull', name: 'רד בול', printName: 'Red Bull', description: '', price: 3, image: dishImage('red-bull') },
        { id: 'heineken', name: 'בירה הייניקן', printName: 'Bira Heineken', description: '', price: 4, image: dishImage('heineken') },
        { id: 'corona', name: 'בירה קורונה', printName: 'Bira Corona', description: '', price: 4, image: dishImage('corona') },
        { id: 'soda', name: 'סודה', printName: 'Soda', description: '', price: 3, image: dishImage('soda') },
        { id: 'water', name: 'מים מינרליים', printName: 'Mayim', description: '', price: 3, image: dishImage('water') },
        {
          id: 'fruit-shake',
          name: 'שייק פירות מרענן',
          printName: 'Shake Perot',
          description: 'על בסיס מים / תפוזים / סודה (בהתאם לפירות הזמינים).',
          price: 8,
          image: dishImage('fruit-shake'),
        },
      ],
    },
    {
      id: 'hotDrinks',
      titleKey: 'categories.hotDrinks',
      items: [
        {
          id: 'espresso',
          name: 'קפה אספרסו',
          printName: 'Cafe Espresso',
          description: '',
          price: 5,
          image: dishImage('black-coffee'),
        },
        {
          id: 'hafukh',
          name: 'קפה הפוך (אפשרות לחלב סויה)',
          printName: 'Cafe Hafukh',
          description: '',
          price: 5,
          image: dishImage('cappuccino'),
        },
        { id: 'black-coffee', name: 'קפה שחור', printName: 'Cafe Shachor', description: '', price: 5, image: dishImage('black-coffee') },
        { id: 'mint-tea', name: 'תה חם עם נענע', printName: 'Te Im Nana', description: '', price: 5, image: dishImage('mint-tea') },
      ],
    },
  ],
};

const HOT_SIDE_ITEMS = [
  { id: 'fries-side', name: "צ'יפס פריך", printName: 'Chips', description: '', price: 0, image: dishImage('fries') },
  { id: 'rice', name: 'אורז לבן', printName: 'Orez Lavan', description: '', price: 0, image: dishImage('white-rice') },
  { id: 'green-beans', name: 'שעועית ירוקה', printName: 'Shayouit Yeruka', description: '', price: 0, image: dishImage('green-beans') },
  { id: 'puree', name: 'פירה', printName: 'Pire', description: '', price: 0, image: dishImage('puree') },
  { id: 'oven-vegetables', name: 'ירקות בתנור', printName: 'Yerakot Batnur', description: '', price: 0, image: dishImage('oven-vegetables') },
];

const MAIN_COURSE_IDS = new Set(['schnitzel', 'chicken-steak', 'whole-fish', 'denis-fillet', 'salmon']);
const HOT_SIDE_IDS = new Set(['fries-side', 'rice', 'green-beans', 'puree', 'oven-vegetables']);
const MAX_SIDES_PER_MAIN = 1;

const SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/lechim_crete/',
  facebook: 'https://www.facebook.com/share/19Pwg3YuSb/?mibextid=wwXIfr',
};

window.MENU_DATA = MENU_DATA;
window.HOT_SIDE_ITEMS = HOT_SIDE_ITEMS;
window.TRANSLATIONS = TRANSLATIONS;
window.DISH_I18N = DISH_I18N;
window.MAIN_COURSE_IDS = MAIN_COURSE_IDS;
window.HOT_SIDE_IDS = HOT_SIDE_IDS;
window.MAX_SIDES_PER_MAIN = MAX_SIDES_PER_MAIN;
window.SOCIAL_LINKS = SOCIAL_LINKS;

