/**
 * Menu data — לחיים בכריתים
 */
const TRANSLATIONS = {
  he: {
    restaurantName: 'לחיים בכריתים',
    pageTitle: 'לחיים בכריתים | תפריט',
    pageDescription: 'תפריט דיגיטלי — לחיים בכריתים, כרתים.',
    bh: 'ב״ה',
    myCart: 'הסל שלי',
    viewMenu: 'לצפייה בתפריט',
    skipToMenu: 'דלג לתפריט',
    myOrder: 'ההזמנה שלי',
    cartEmpty: 'הסל ריק הוסיפו מנות מהתפריט',
    total: 'סה״כ',
    clearCart: 'רוקן סל',
    addToCart: 'הוסף לסל',
    addedToCart: '{name} נוסף לסל',
    decrease: 'הפחת כמות',
    increase: 'הוסף כמות',
    close: 'סגור',
    openCart: 'פתח סל הזמנה',
    openMenu: 'פתח תפריט',
    showDish: 'הצג פרטים על {name}',
    perUnit: '{price} ליחידה',
    currency: '€',
    langToggleAria: 'החלפת שפה – עברית / English',
    mainsNote: 'כל המנות העיקריות מוגשות עם בחירה בין שתי תוספות חמות (למעט מנת הנודלס).',
    sideForMain: 'תוספת ל־{name}',
    servedWith: 'מוגש עם: {sides}',
    maxSidesPerMain: 'ניתן לבחור עד שתי תוספות חמות לכל מנה עיקרית',
    chooseMainFirst: 'יש לבחור מנה עיקרית לפני תוספת חמה',
    chooseSidesTitle: 'בחרו תוספות חמות',
    chooseSidesSubtitle: 'עד 2 תוספות למנה: {name}',
    sidesSelected: '{count} מתוך 2 נבחרו',
    sidesContinue: 'המשך',
    sideLabel: 'תוספת',
    contact: 'יצירת קשר',
    hours: 'שעות פעילות',
    hoursDays: 'א׳ – ה׳',
    address: 'כתובת',
    addressText: 'Analipsi 700 14, Greece',
    copyright: 'כל הזכויות שמורות',
    footerTagline: 'The Pearl of Crete',
    followUs: 'עקבו אחרינו',
    categories: {
      starters: 'ראשונות ונשנושים',
      mains: 'מנות עיקריות',
      hotSides: 'תוספות חמות לבחירה',
      salads: 'סלטים וטורטיות',
      desserts: 'קינוחים',
      coldDrinks: 'שתייה קלה',
      hotDrinks: 'שתייה חמה',
    },
  },
  en: {
    restaurantName: 'LeChaim in Keri',
    pageTitle: 'LeChaim in Keri | Menu',
    pageDescription: 'Digital menu — LeChaim in Keri, Crete.',
    bh: 'B"H',
    myCart: 'My Cart',
    viewMenu: 'View Menu',
    skipToMenu: 'Skip to menu',
    myOrder: 'My Order',
    cartEmpty: 'Your cart is empty — add dishes from the menu',
    total: 'Total',
    clearCart: 'Clear cart',
    addToCart: 'Add to cart',
    addedToCart: '{name} added to cart',
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
    close: 'Close',
    openCart: 'Open order cart',
    openMenu: 'Open menu',
    showDish: 'View details for {name}',
    perUnit: '{price} each',
    currency: '€',
    langToggleAria: 'Switch language – Hebrew / English',
    mainsNote: 'All main courses are served with a choice of two hot sides (except noodles).',
    sideForMain: 'Side for {name}',
    servedWith: 'Served with: {sides}',
    maxSidesPerMain: 'Up to two hot sides per main course',
    chooseMainFirst: 'Choose a main course before adding a hot side',
    chooseSidesTitle: 'Choose hot sides',
    chooseSidesSubtitle: 'Up to 2 sides for: {name}',
    sidesSelected: '{count} of 2 selected',
    sidesContinue: 'Continue',
    sideLabel: 'Side',
    contact: 'Contact',
    hours: 'Opening Hours',
    hoursDays: 'Sun – Thu',
    address: 'Address',
    addressText: 'Analipsi 700 14, Greece',
    copyright: 'All rights reserved',
    footerTagline: 'The Pearl of Crete',
    followUs: 'Follow us',
    categories: {
      starters: 'Starters & Snacks',
      mains: 'Main Courses',
      hotSides: 'Hot Sides',
      salads: 'Salads & Tortillas',
      desserts: 'Desserts',
      coldDrinks: 'Soft Drinks',
      hotDrinks: 'Hot Drinks',
    },
  },
};

const DISH_I18N = {
  en: {
    'salad-plate': { name: 'Opening Salad Platter', desc: 'Selection of refreshing house salads with warm pitas (recommended for the table center)' },
    hummus: { name: 'House Hummus', desc: 'Creamy handmade hummus served with olive oil, cumin and pitas' },
    antipasti: { name: 'Colorful Antipasti', desc: 'Seasonal vegetables roasted in the oven with herbs' },
    mushrooms: { name: 'Hot Mushrooms', desc: 'Fresh mushrooms sautéed in garlic, olive oil and parsley' },
    'fries-classic': { name: 'Classic Fries', desc: 'Crispy potato fries' },
    'fries-side': { name: 'Crispy Fries', desc: '' },
    schnitzel: { name: "Chef's Schnitzel", desc: 'Crispy chicken breast in golden breadcrumb coating' },
    'chicken-steak': { name: 'Grilled Chicken Steak', desc: 'Juicy chicken cuts with Mediterranean seasoning' },
    denis: { name: 'Baked Sea Bream Fillet', desc: 'Fresh sea bream baked with herbs and olive oil' },
    salmon: { name: 'Seared Salmon', desc: 'Salmon fillet with light glaze' },
    noodles: { name: 'Asian Salmon Noodles', desc: 'Stir-fried noodles with salmon, vegetables, soy and ginger sauce' },
    'white-rice': { name: 'Juicy White Rice', desc: 'Fluffy white rice' },
    'green-beans': { name: 'Sautéed Green Beans', desc: 'Green beans sautéed in garlic oil' },
    'baked-potatoes': { name: 'Baked Potatoes', desc: 'Oven-baked potatoes' },
    'tortilla-salmon': { name: 'Salmon & Avocado Tortilla', desc: 'Quality salmon, creamy avocado, vegetables and delicate sauce in a warm tortilla' },
    'chicken-salad': { name: 'Rich Chicken Salad', desc: 'Warm chicken on lettuce with seasonal vegetables and vinaigrette' },
    'israeli-salad': { name: 'Israeli Chopped Salad with Herbs', desc: '' },
    'green-salad': { name: 'Green Leaf Salad with Vinaigrette', desc: '' },
    'fruit-plate': { name: 'Seasonal Fruit Platter', desc: 'Selection of fresh, refreshing cut fruits' },
    coke: { name: 'Coca-Cola', desc: '' },
    'coke-zero': { name: 'Coke Zero', desc: '' },
    fuzetea: { name: 'Fuze Tea', desc: '' },
    soda: { name: 'Soda', desc: '' },
    water: { name: 'Mineral Water', desc: '' },
    'fruit-shake': { name: 'Refreshing Fruit Shake', desc: "Water / orange / soy base (ask the waiter about today's fruits)" },
    espresso: { name: 'Espresso', desc: '' },
    cappuccino: { name: 'Cappuccino', desc: '(soy milk available)' },
    'black-coffee': { name: 'Black Coffee', desc: '' },
    'mint-tea': { name: 'Hot Mint Tea', desc: '' },
    'iced-coffee': { name: 'Iced Coffee', desc: '(soy milk base)' },
  },
};

function dishImage(id) {
  return `assets/images/dishes/${id}.webp`;
}

const MENU_DATA = {
  restaurant: 'לחיים בכריתים',
  categories: [
    {
      id: 'starters',
      titleKey: 'categories.starters',
      items: [
        { id: 'salad-plate', name: 'פלטת סלטים פתיחה', description: 'מבחר סלטי הבית המרעננים לצד פיתות חמות (מומלץ למרכז שולחן).', price: 12, image: dishImage('salad-plate') },
        { id: 'hummus', name: 'חומוס הבית', description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ופיתות.', price: 12, image: dishImage('hummus') },
        { id: 'antipasti', name: 'אנטיפסטי צבעוני', description: 'לקט ירקות העונה קלויים בתנור עם עשבי תיבול.', price: 12, image: dishImage('antipasti') },
        { id: 'mushrooms', name: 'פטריות חמות', description: 'פטריות טריות מוקפצות בשום, שמן זית ופטרוזיליה.', price: 8, image: dishImage('mushrooms') },
        { id: 'fries-classic', name: "צ'יפס קלאסי", description: 'מנת תפוחי אדמה פריכים.', price: 8, image: dishImage('fries') },
      ],
    },
    {
      id: 'mains',
      titleKey: 'categories.mains',
      descriptionKey: 'mainsNote',
      items: [
        { id: 'schnitzel', name: 'השניצל של השף', description: 'חזה עוף פריך בציפוי פירורי לחם מוזהבים.', price: 22, image: dishImage('schnitzel') },
        { id: 'chicken-steak', name: 'סטייק פרגית בגריל', description: 'נתחי פרגית עסיסיים בתיבול ים-תיכוני.', price: 24, image: dishImage('chicken-steak') },
        { id: 'denis', name: 'דניס בתנור', description: 'דניס טרי אפוי עם עשבי תיבול ושמן זית.', price: 27, image: dishImage('denis') },
        { id: 'salmon', name: 'נתח סלמון צרוב', description: 'פילה סלמון בזיגוג עדין.', price: 29, image: dishImage('salmon') },
        { id: 'noodles', name: 'נודלס סלמון אסייתי', description: "אטריות מוקפצות עם נתחי סלמון וירקות ברוטב סויה וג'ינג'ר.", price: 18, image: dishImage('noodles') },
      ],
    },
    {
      id: 'salads',
      titleKey: 'categories.salads',
      items: [
        { id: 'tortilla-salmon', name: 'טורטייה סלמון ואבוקדו', description: 'סלמון איכותי, אבוקדו קרמי, ירקות ורוטב עדין עטופים בטורטייה חמה.', price: 14, image: dishImage('tortilla-salmon') },
        { id: 'chicken-salad', name: 'סלט פרגית עשיר', description: 'נתחי פרגית חמים על מצע חסות, ירקות העונה ורוטב ויניגרט.', price: 14, image: dishImage('chicken-salad') },
        { id: 'israeli-salad', name: 'סלט קצוץ ישראלי עם עשבי תיבול', description: '', price: 9, image: dishImage('israeli-salad') },
        { id: 'green-salad', name: 'סלט עלים ירוקים עם רוטב וינגרט', description: '', price: 9, image: dishImage('green-salad') },
      ],
    },
    {
      id: 'desserts',
      titleKey: 'categories.desserts',
      items: [
        { id: 'fruit-plate', name: 'פלטת פירות העונה', description: 'מבחר פירות טריים, מרעננים וחתוכים.', price: 18, image: dishImage('fruit-plate') },
      ],
    },
    {
      id: 'coldDrinks',
      titleKey: 'categories.coldDrinks',
      items: [
        { id: 'coke', name: 'קוקה קולה', description: '', price: 2, image: dishImage('coke') },
        { id: 'coke-zero', name: 'קולה זירו', description: '', price: 2, image: dishImage('coke-zero') },
        { id: 'fuzetea', name: 'פיוזטי', description: '', price: 2, image: dishImage('fuzetea') },
        { id: 'soda', name: 'סודה', description: '', price: 2, image: dishImage('soda') },
        { id: 'water', name: 'מים מינרליים', description: '', price: 2, image: dishImage('water') },
        { id: 'fruit-shake', name: 'שייק פירות מרענן', description: 'על בסיס מים / תפוזים / סויה (שאלו את המלצר על הפירות של היום).', price: 8, image: dishImage('fruit-shake') },
      ],
    },
    {
      id: 'hotDrinks',
      titleKey: 'categories.hotDrinks',
      items: [
        { id: 'espresso', name: 'אספרסו', description: '', price: 5, image: dishImage('espresso') },
        { id: 'cappuccino', name: 'קפה הפוך', description: '(אפשרות לחלב סויה).', price: 5, image: dishImage('cappuccino') },
        { id: 'black-coffee', name: 'קפה שחור', description: '', price: 5, image: dishImage('black-coffee') },
        { id: 'mint-tea', name: 'תה חם עם נענע', description: '', price: 5, image: dishImage('mint-tea') },
        { id: 'iced-coffee', name: 'קפה קר מרענן', description: '(על בסיס חלב סויה).', price: 8, image: dishImage('iced-coffee') },
      ],
    },
  ],
};

const HOT_SIDE_ITEMS = [
  { id: 'fries-side', name: "צ'יפס פריך", description: '', price: 0, image: dishImage('fries') },
  { id: 'white-rice', name: 'אורז לבן עסיסי', description: '', price: 0, image: dishImage('white-rice') },
  { id: 'baked-potatoes', name: 'תפוחי אדמה אפויים', description: '', price: 0, image: dishImage('baked-potatoes') },
  { id: 'green-beans', name: 'שעועית ירוקה מוקפצת', description: '', price: 0, image: dishImage('green-beans') },
];

const MAIN_COURSE_IDS = new Set(['schnitzel', 'chicken-steak', 'denis', 'salmon']);
const HOT_SIDE_IDS = new Set(['fries-side', 'white-rice', 'baked-potatoes', 'green-beans']);
const MAX_SIDES_PER_MAIN = 2;

const SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/',
  facebook: 'https://www.facebook.com/',
};
