/**
 * Menu data — לחיים בכריתים
 */
const TRANSLATIONS = {
  he: {
    restaurantName: 'לחיים בכריתים',
    pageTitle: 'מסעדת לחיים | מסעדה כשרה למהדרין בכרתים',
    pageDescription: 'תפריט דיגיטלי — לחיים בכריתים, כרתים.',
    bh: 'ב״ה',
    myCart: 'הסל שלי',
    myOrderView: 'ההזמנה שלי',
    takeawayLockedToast: 'יש לכם הזמנה פתוחה — אפשר להוסיף פריטים לאותה הזמנה בלבד',
    takeawayLockedAction: 'הזמנה פתוחה — הוסיפו פריטים לאותה הזמנה',
    tableLabel: 'שולחן',
    changeTableAria: 'שנה מספר שולחן',
    backToOrderType: 'חזרה',
    backToOrderTypeAria: 'חזרה לבחירת סוג הזמנה',
    viewMenu: 'צפייה בתפריט',
    heroWelcome: 'ברוכים הבאים',
    heroTitle: 'מסעדת לחיים בכרתים',
    heroKosher: 'כשר למהדרין',
    heroTagline: '',
    skipToMenu: 'דלג לתפריט',
    myOrder: 'ההזמנה שלי',
    cartEmpty: 'העגלה ריקה',
    total: 'סה״כ',
    currentTotal: 'סה״כ עגלה',
    clearCart: 'נקה עגלה',
    clearCartConfirm: 'למחוק את כל המוצרים מהעגלה?',
    sendOrder: 'שלח הזמנה',
    sendingOrder: 'שולח...',
    orderSentSuccess: 'ההזמנה נשלחה בהצלחה למטבח',
    orderSentFail: 'שליחת ההזמנה נכשלה\nנסה שוב',
    receiptTitle: 'ההזמנה נשלחה',
    receiptEyebrow: 'כרטיס הזמנה',
    receiptContinue: 'הוסף פריטים להזמנה קיימת',
    receiptNewOrder: 'הזמנה חדשה',
    receiptClose: 'סגור',
    orderingClosedBanner: 'ההזמנות פתוחות א׳–ה׳ בין 14:00 ל־22:00. שישי–שבת סגור. כרגע ניתן לצפות בתפריט בלבד.',
    orderingClosedToast: 'לא ניתן להזמין כרגע — פתוח א׳–ה׳ 14:00–22:00',
    orderingClosedAction: 'לא ניתן להוסיף לעגלה כרגע',
    kitchenClosedModal: 'המטבח סגור כרגע. לא ניתן להוסיף מנות.',
    kitchenCountdownModal: 'היי, המטבח נסגר בעוד {time}. תרצו להזמין משהו?',
    kitchenClosedBanner: 'המטבח סגור כרגע — לא ניתן להוסיף מנות בישיבה במקום.',
    kitchenClosingCountdown: 'המטבח נסגר בעוד {time}',
    kitchenClosingOk: 'הבנתי',
    receiptTotal: 'סה״כ להזמנה זו',
    receiptTable: 'שולחן {n}',
    receiptTakeaway: 'איסוף עצמי',
    receiptOrderNo: 'מספר הזמנה',
    receiptRememberNo: 'המסעדה מיד תיצור איתכם קשר על מנת לאשר את ההזמנה',
    receiptPickupAsap: 'איסוף: בהקדם',
    receiptPickupAt: 'איסוף: {time}',
    receiptEmpty: 'אין פריטים',
    requestBill: 'בקש חשבון',
    requestBillConfirm: 'האם ברצונך לבקש חשבון?',
    requestBillYes: 'כן',
    requestBillCancel: 'ביטול',
    requestBillSuccess: 'בקשת החשבון נשלחה למלצר',
    requestBillFail: 'לא ניתן לבקש חשבון',
    requestBillNoOrder: 'אין הזמנה פעילה לשולחן',
    couponAsk: 'יש לך קוד קופון?',
    couponApply: 'החל קופון',
    couponPlaceholder: 'קוד קופון',
    couponOk: 'קופון אומת בהצלחה\n{percent}% הנחה הוחלה על ההזמנה',
    couponFail: 'קוד קופון לא תקין',
    couponSubtotal: 'סה״כ לפני הנחה',
    couponDiscount: 'הנחת קופון ({percent}%)',
    couponPay: 'לתשלום',
    tableChangeLocked: 'לא ניתן להחליף שולחן לאחר שליחת הזמנה',
    clearCartYes: 'כן, רוקן',
    clearCartCancel: 'ביטול',
    addToCart: 'הוסף לסל',
    addedToCart: '{name} נוסף לסל',
    outOfStock: 'אזל מהמלאי',
    decrease: 'הפחת כמות',
    increase: 'הוסף כמות',
    close: 'סגור',
    openCart: 'פתח סל הזמנה',
    openMyOrder: 'פתח את ההזמנה שלי',
    openMenu: 'פתח תפריט',
    showDish: 'הצג פרטים על {name}',
    perUnit: '{price} ליחידה',
    perKg: '{price} / ק״ג',
    pricePerKgBadge: 'מחיר לק״ג',
    weightLabel: 'משקל',
    weightOption: '{kg} ק״ג',
    frozenPackLabel: 'אריזה קפואה',
    packWeightLabel: 'משקל ממוצע:',
    packWeightValue: '980 - 1.2 ק״ג',
    packWeightRange: 'משקל ממוצע: 980 - 1.2 ק״ג',
    packEstPriceLabel: 'מחיר משוער לחבילה',
    packEstPrice: '{min} – {max}',
    packQtyLabel: '{count} חבילות',
    packQtyLabelOne: '1 חבילה',
    packQtyControlLabel: 'כמות חבילות',
    thawPacksLabel: 'כמה חבילות להפשיר?',
    thawPacksShort: 'להפשיר: {count}',
    frozenStateLabel: 'קפוא',
    thawedStateLabel: 'מופשר',
    packEstLine: 'מחיר משוער: {min} – {max}',
    deliveryFeeLine: 'משלוח – {price}',
    cartEstTotal: '{min} – {max}',
    cartEstTotalLabel: 'סה״כ משוער',
    butcherNoticeTitle: 'שימו לב',
    butcherNoticeBody: 'כל מוצרי הבשר נמכרים באריזות קפואות.\nמשקל כל אריזה משתנה בדרך כלל בין 980 גרם ל־1.2 ק״ג.\nהמחיר הסופי יחושב לפי המשקל בפועל של האריזות שנבחרו.\nהמחירים באתר הם מחירים משוערים בלבד.',
    butcherCheckoutTitle: 'פרטי הזמנה',
    butcherCheckoutHint: 'לשליחת ההזמנה נדרשים פרטי לקוח ומועד',
    butcherCheckoutName: 'שם מלא *',
    butcherCheckoutPhone: 'טלפון *',
    butcherCheckoutNotes: 'הערות (אופציונלי)',
    butcherCheckoutSubmit: 'שלח הזמנה',
    butcherCheckoutNameRequired: 'נא להזין שם מלא',
    butcherCheckoutPhoneRequired: 'נא להזין מספר טלפון',
    butcherCheckoutPhoneInvalid: 'מספר טלפון לא תקין',
    butcherCheckoutAsap: 'אני רוצה שההזמנה תהיה מוכנה בהקדם האפשרי',
    butcherCheckoutDate: 'תאריך איסוף *',
    butcherCheckoutTime: 'שעת איסוף *',
    butcherCheckoutDateDelivery: 'תאריך משלוח *',
    butcherCheckoutTimeDelivery: 'שעת משלוח מועדפת *',
    butcherCheckoutDateRequired: 'נא לבחור תאריך',
    butcherCheckoutTimeRequired: 'נא לבחור שעה',
    butcherHeroTitle: 'חנות הבשר של לחיים',
    butcherHeroSubtitle: 'בשר חלק כשר למהדרין • שחיטת ליובאוויטש • כשרות מהודרת',
    butcherHeroDesc: 'אצלנו תוכלו להזמין מגוון נתחי בשר ועוף איכותיים, טריים וכשרים למהדרין.\n\nכל המוצרים נבחרים בקפידה ומסופקים תחת סטנדרטים גבוהים של איכות וכשרות.\n\nשימו לב: כל המוצרים קפואים. ניתן לסמן וי אם ברצונכם מופשר.',
    deliveryFeeNotice: 'עלות המשלוח היא €10 · מינימום הזמנה €75 (לא כולל משלוח)',
    deliveryMinOrder: 'מינימום הזמנה למשלוח €75 (לא כולל משלוח)',
    takeawayCheckoutTitle: 'פרטי הזמנה',
    takeawayCheckoutHint: 'לשליחת ההזמנה נדרשים פרטי לקוח ומועד',
    fulfillmentType: 'סוג הזמנה',
    fulfillmentPickup: 'איסוף עצמי',
    fulfillmentDelivery: 'משלוח',
    customerAddress: 'כתובת *',
    customerAddressRequired: 'נא להזין כתובת למשלוח',
    gotIt: 'הבנתי',
    receiptButcher: 'חנות בשר',
    receiptButcherPickupAsap: 'איסוף: בהקדם האפשרי',
    receiptButcherPickupDate: 'תאריך איסוף: {date}',
    receiptButcherPickupTime: 'שעת איסוף: {time}',
    receiptButcherDelivery: 'משלוח',
    receiptButcherDeliveryFee: 'עלות משלוח: {price}',
    currency: '€',
    langToggleAria: 'החלפת שפה – עברית / English',
    nonAlcoholicLabel: 'בלי אלכוהול',
    recommended: 'מומלץ',
    mainsNote: 'כל המנות העיקריות מוגשות עם תוספת אחת חמה.',
    mainsSidesTitle: 'תוספות לבחירה',
    mainsSidesList: "צ'יפס פריך | אורז לבן | שעועית ירוקה | פירה",
    sidesIncluded: 'כלול',
    sidesIncludedNote: 'כלול במנה העיקרית',
    sideForMain: 'תוספת ל־{name}',
    servedWith: 'מוגש עם: {sides}',
    maxSidesPerMain: 'ניתן לבחור תוספת חמה אחת לכל מנה עיקרית',
    chooseMainFirst: 'יש לבחור מנה עיקרית לפני תוספת חמה',
    chooseSidesTitle: 'בחרו תוספת חמה',
    chooseSidesSubtitle: 'תוספת אחת למנה: {name}',
    sidesSelected: '{count} מתוך 1 נבחרו',
    sidesContinue: 'המשך',
    sideLabel: 'תוספת',
    chooseShakeBaseTitle: 'מה אתם מעדיפים?',
    chooseShakeBaseSubtitle: 'בחרו בסיס לשייק: {name}',
    shakeBaseLabel: 'בסיס',
    chooseLimonanaAlcoholTitle: 'עם אלכוהול?',
    chooseLimonanaAlcoholSubtitle: '{name}',
    limonanaAlcoholLabel: 'אלכוהול',
    chooseDrinkTitle: 'בחרו שתייה',
    chooseDrinkSubtitle: 'שתייה כלולה במנה: {name}',
    drinkIncludedLabel: 'שתייה',
    contact: 'יצירת קשר',
    hours: 'שעות פעילות',
    hoursDays: 'א׳ – ה׳',
    address: 'כתובת',
    addressText: 'Analipsi 700 14, Greece',
    copyright: 'מסעדת לחיים בכרתים כשר למהדרין',
    footerTagline: 'The Pearl of Crete',
    followUs: 'עקבו אחרינו',
    categories: {
      starters: 'ראשונות ונשנושים',
      specials: 'הספיישלים של לחיים',
      mains: 'מנות עיקריות',
      hotSides: 'תוספות חמות לבחירה',
      salads: 'סלטים',
      cocktails: 'שייקים/קוקטיילים',
      coldDrinks: 'שתייה קלה',
      hotDrinks: 'שתייה חמה',
      desserts: 'קינוחים',
      butcher: 'בשרים',
      poultry: 'עופות',
      shakeBases: 'בסיסי שייק פירות',
    },
  },
  en: {
    restaurantName: 'LeChaim in Keri',
    pageTitle: 'Lechaim Restaurant | Mehadrin Kosher Restaurant in Crete',
    pageDescription: 'Digital menu — LeChaim in Keri, Crete.',
    bh: 'B"H',
    myCart: 'My Cart',
    myOrderView: 'My order',
    takeawayLockedToast: 'You have an open order — you can only add items to that order',
    takeawayLockedAction: 'Open order — add items to the same order',
    tableLabel: 'Table',
    changeTableAria: 'Change table number',
    backToOrderType: 'Back',
    backToOrderTypeAria: 'Back to order type selection',
    viewMenu: 'View Menu',
    heroWelcome: 'Welcome',
    heroTitle: 'Lechaim Restaurant in Crete',
    heroKosher: 'Mehadrin Kosher',
    heroTagline: '',
    skipToMenu: 'Skip to menu',
    myOrder: 'My Order',
    cartEmpty: 'Cart is empty',
    total: 'Total',
    currentTotal: 'Cart total',
    clearCart: 'Clear cart',
    clearCartConfirm: 'Remove all items from the cart?',
    sendOrder: 'Send order',
    sendingOrder: 'Sending...',
    orderSentSuccess: 'Order sent successfully to the kitchen',
    orderSentFail: 'Failed to send order\nTry again',
    receiptTitle: 'Order sent',
    receiptEyebrow: 'Order card',
    receiptContinue: 'Add items to existing order',
    receiptNewOrder: 'New order',
    receiptClose: 'Close',
    orderingClosedBanner: 'Ordering is open Sun–Thu 14:00–22:00. Closed Fri–Sat. You can browse the menu only right now.',
    orderingClosedToast: 'Ordering is closed — open Sun–Thu 14:00–22:00',
    orderingClosedAction: 'Ordering is unavailable right now',
    kitchenClosedModal: 'The kitchen is closed right now. You cannot add dishes.',
    kitchenCountdownModal: 'Hi, the kitchen is closing in {time}. Would you like to order something?',
    kitchenClosedBanner: 'The kitchen is closed — you cannot add dine-in dishes.',
    kitchenClosingCountdown: 'Kitchen closes in {time}',
    kitchenClosingOk: 'Got it',
    receiptTotal: 'Total for this order',
    receiptTable: 'Table {n}',
    receiptTakeaway: 'Takeaway',
    receiptOrderNo: 'Order number',
    receiptRememberNo: 'The restaurant will contact you shortly to confirm your order',
    receiptPickupAsap: 'Pickup: ASAP',
    receiptPickupAt: 'Pickup: {time}',
    receiptEmpty: 'No items',
    requestBill: 'Request bill',
    requestBillConfirm: 'Would you like to request the bill?',
    requestBillYes: 'Yes',
    requestBillCancel: 'Cancel',
    requestBillSuccess: 'Bill request sent to the waiter',
    requestBillFail: 'Could not request the bill',
    requestBillNoOrder: 'No active order for this table',
    couponAsk: 'Have a coupon code?',
    couponApply: 'Apply coupon',
    couponPlaceholder: 'Coupon code',
    couponOk: 'Coupon verified\n{percent}% discount applied',
    couponFail: 'Invalid coupon code',
    couponSubtotal: 'Subtotal',
    couponDiscount: 'Coupon discount ({percent}%)',
    couponPay: 'Amount due',
    tableChangeLocked: 'Table cannot be changed after an order is sent',
    clearCartYes: 'Yes, clear',
    clearCartCancel: 'Cancel',
    addToCart: 'Add to cart',
    addedToCart: '{name} added to cart',
    outOfStock: 'Out of stock',
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
    close: 'Close',
    openCart: 'Open order cart',
    openMyOrder: 'Open my order',
    openMenu: 'Open menu',
    showDish: 'View details for {name}',
    perUnit: '{price} each',
    perKg: '{price} / kg',
    pricePerKgBadge: 'Price per kg',
    weightLabel: 'Weight',
    weightOption: '{kg} kg',
    frozenPackLabel: 'Frozen pack',
    packWeightLabel: 'Average weight:',
    packWeightValue: '980 - 1.2 kg',
    packWeightRange: 'Average weight: 980 - 1.2 kg',
    packEstPriceLabel: 'Estimated pack price',
    packEstPrice: '{min} – {max}',
    packQtyLabel: '{count} packs',
    packQtyLabelOne: '1 pack',
    packQtyControlLabel: 'Number of packs',
    thawPacksLabel: 'How many packs to thaw?',
    thawPacksShort: 'Thaw: {count}',
    frozenStateLabel: 'Frozen',
    thawedStateLabel: 'Thawed',
    packEstLine: 'Estimated: {min} – {max}',
    deliveryFeeLine: 'Delivery – {price}',
    cartEstTotal: '{min} – {max}',
    cartEstTotalLabel: 'Estimated total',
    butcherNoticeTitle: 'Please note',
    butcherNoticeBody: 'All meat products are sold in frozen packs.\nEach pack typically weighs between 980 g and 1.2 kg.\nThe final price is calculated from the actual weight of the packs selected.\nPrices shown are estimates only.',
    butcherCheckoutTitle: 'Order details',
    butcherCheckoutHint: 'Customer details and schedule are required to send the order',
    butcherCheckoutName: 'Full name *',
    butcherCheckoutPhone: 'Phone *',
    butcherCheckoutNotes: 'Notes (optional)',
    butcherCheckoutSubmit: 'Send order',
    butcherCheckoutNameRequired: 'Please enter your full name',
    butcherCheckoutPhoneRequired: 'Please enter a phone number',
    butcherCheckoutPhoneInvalid: 'Invalid phone number',
    butcherCheckoutAsap: 'I want the order ready as soon as possible',
    butcherCheckoutDate: 'Pickup date *',
    butcherCheckoutTime: 'Pickup time *',
    butcherCheckoutDateDelivery: 'Delivery date *',
    butcherCheckoutTimeDelivery: 'Preferred delivery time *',
    butcherCheckoutDateRequired: 'Please choose a date',
    butcherCheckoutTimeRequired: 'Please choose a time',
    butcherHeroTitle: 'Lechaim Butcher Shop',
    butcherHeroSubtitle: 'Mehadrin Chalak meat • Lubavitch shechita • Premium kashrut',
    butcherHeroDesc: 'Order a selection of quality meat and chicken cuts — fresh and Mehadrin kosher.\n\nAll products are carefully selected and supplied under high standards of quality and kashrut.\n\nPlease note: all products are frozen. Check the box if you want them thawed.',
    deliveryFeeNotice: 'Delivery fee is €10 · minimum order €75 (excluding delivery)',
    deliveryMinOrder: 'Minimum delivery order €75 (excluding delivery)',
    takeawayCheckoutTitle: 'Order details',
    takeawayCheckoutHint: 'Customer details and pickup time are required to send the order',
    fulfillmentType: 'Order type',
    fulfillmentPickup: 'Takeaway',
    fulfillmentDelivery: 'Delivery',
    customerAddress: 'Address *',
    customerAddressRequired: 'Please enter a delivery address',
    gotIt: 'Got it',
    receiptButcher: 'Butcher shop',
    receiptButcherPickupAsap: 'Pickup: as soon as possible',
    receiptButcherPickupDate: 'Pickup date: {date}',
    receiptButcherPickupTime: 'Pickup time: {time}',
    receiptButcherDelivery: 'Delivery',
    receiptButcherDeliveryFee: 'Delivery fee: {price}',
    currency: '€',
    langToggleAria: 'Switch language – Hebrew / English',
    nonAlcoholicLabel: 'non-alcoholic',
    recommended: 'Recommended',
    mainsNote: 'All main courses are served with one hot side.',
    mainsSidesTitle: 'Sides to choose from',
    mainsSidesList: 'Crispy fries | White rice | Green beans | Mashed potatoes',
    sidesIncluded: 'Included',
    sidesIncludedNote: 'Included with the main course',
    sideForMain: 'Side for {name}',
    servedWith: 'Served with: {sides}',
    maxSidesPerMain: 'One hot side per main course',
    chooseMainFirst: 'Choose a main course before adding a hot side',
    chooseSidesTitle: 'Choose a hot side',
    chooseSidesSubtitle: 'One side for: {name}',
    sidesSelected: '{count} of 1 selected',
    sidesContinue: 'Continue',
    sideLabel: 'Side',
    chooseShakeBaseTitle: 'What do you prefer?',
    chooseShakeBaseSubtitle: 'Choose a base for: {name}',
    shakeBaseLabel: 'Base',
    chooseLimonanaAlcoholTitle: 'With alcohol?',
    chooseLimonanaAlcoholSubtitle: '{name}',
    limonanaAlcoholLabel: 'Alcohol',
    chooseDrinkTitle: 'Choose a drink',
    chooseDrinkSubtitle: 'Drink included with: {name}',
    drinkIncludedLabel: 'Drink',
    contact: 'Contact',
    hours: 'Opening Hours',
    hoursDays: 'Sun – Thu',
    address: 'Address',
    addressText: 'Analipsi 700 14, Greece',
    copyright: 'Lechaim Restaurant in Crete — Mehadrin Kosher',
    footerTagline: 'The Pearl of Crete',
    followUs: 'Follow us',
    categories: {
      starters: 'Starters & Snacks',
      specials: "Lechaim's Specials",
      mains: 'Main Courses',
      hotSides: 'Hot Sides to Choose',
      salads: 'Salads',
      cocktails: 'Shakes / Cocktails',
      coldDrinks: 'Soft Drinks',
      hotDrinks: 'Hot Drinks',
      desserts: 'Desserts',
      butcher: 'Meats',
      poultry: 'Poultry',
      shakeBases: 'Fruit shake bases',
    },
  },
  el: {
    currentTotal: 'Τρέχον Σύνολο',
    requestBill: 'Λογαριασμός',
    requestBillConfirm: 'Θέλετε να ζητήσετε τον λογαριασμό;',
    requestBillYes: 'Ναι',
    requestBillCancel: 'Ακύρωση',
    requestBillSuccess: 'Το αίτημα λογαριασμού στάλθηκε στον σερβιτόρο',
    requestBillFail: 'Δεν ήταν δυνατή η αίτηση λογαριασμού',
    requestBillNoOrder: 'Δεν υπάρχει ενεργή παραγγελία',
    tableChangeLocked: 'Δεν μπορείτε να αλλάξετε τραπέζι μετά την αποστολή παραγγελίας',
    clearCartYes: 'Ναι, άδειασμα',
    clearCartCancel: 'Ακύρωση',
  },
};

const DISH_I18N = {
  en: {
    'salad-plate': {
      name: 'Opening Salad Platter',
      desc: 'Selection of refreshing house salads with warm bread (recommended for the table center).',
    },
    'hatzil-patuach': {
      name: 'Open Eggplant for the Table Center',
      desc: 'Open Baladi eggplant with tahini on top and cilantro.',
    },
    hummus: {
      name: 'House Hummus',
      desc: 'Creamy handmade hummus, served with olive oil, cumin and bread.',
    },
    'hummus-egg': {
      name: 'Hummus with Egg',
      desc: 'Creamy handmade hummus, served with olive oil, cumin and bread, topped with egg.',
    },
    'hummus-meat': {
      name: 'Hummus with Meat',
      desc: 'Creamy handmade hummus, served with olive oil, cumin and bread, topped with meat.',
    },
    bread: {
      name: 'Bread',
      desc: '',
    },
    mushrooms: {
      name: 'Hot Mushrooms',
      desc: 'Fresh mushrooms sautéed in garlic, olive oil and parsley.',
    },
    'fries-classic': {
      name: 'Classic Fries',
      desc: 'Crispy potato fries.',
    },
    schnitzel: {
      name: "Chef's Schnitzel",
      desc: 'Crispy chicken breast in golden breadcrumb coating.',
    },
    'chicken-steak': {
      name: 'Grilled Chicken Steak',
      desc: 'Juicy chicken cut with Mediterranean seasoning.',
    },
    'staik-antarkot': {
      name: 'Premium Entrecote Steak',
      desc: 'Premium entrecote steak 300g, grilled medium, served with grilled vegetables, chimichurri and sweet potato cream.',
    },
    asado: {
      name: 'Fall-off-the-bone Asado',
      desc: 'Slow-cooked asado, 600–700g, until the meat is tender and falls off the bone, served with grilled vegetables, chimichurri and sweet potato cream.',
    },
    'whole-fish': {
      name: 'Whole Baked Sea Bream',
      desc: 'Fresh sea bream baked with herbs and olive oil.',
    },
    'denis-fillet': {
      name: 'Oven-Baked Sea Bream Fillet',
      desc: 'Sea bream fillet baked with green herbs and olive oil.',
    },
    salmon: {
      name: 'Oven-Baked Salmon',
      desc: 'Salmon fillet baked with delicate seasoning.',
    },
    kebab: {
      name: 'Kebab Skewers',
      desc: 'Served with tahini and a small side salad.',
    },
    'chicken-stirfry': {
      name: 'Stir-Fried Chicken',
      desc: 'Chicken pieces stir-fried with vegetables in soy and ginger sauce.',
    },
    'hamburger-fries': {
      name: 'Hamburger & Fries',
      desc: 'Hamburger patty in a bun with tomato, lettuce and sauces on the side, including fries and a drink of your choice.',
    },
    'chicken-salad': {
      name: 'Chicken Salad',
      desc: 'Chicken pieces on a fresh vegetable salad.',
    },
    'butcher-asado': {
      name: 'Asado',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'butcher-entrecote-premium': {
      name: 'Entrecote',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'butcher-goulash': {
      name: 'Goulash',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'butcher-chicken-schnitzel': {
      name: 'Chicken Schnitzel',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'butcher-chicken-leg': {
      name: 'Chicken Legs',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'butcher-pargit-skinless': {
      name: 'Skinless Pargit',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'butcher-wings-drumettes': {
      name: 'Wings',
      desc: 'Mehadrin kosher -\nLubavitch shechita',
    },
    'israeli-salad': {
      name: 'Israeli Salad',
      desc: 'Fresh vegetable salad.',
    },
    'green-salad': {
      name: 'Green Salad',
      desc: 'Selection of fresh leaves with vinaigrette.',
    },
    'market-salad': {
      name: 'Market Salad',
      desc: 'Fresh seasonal vegetables.',
    },
    'fruit-plate': {
      name: 'Seasonal Fruit Platter',
      desc: 'Selection of fresh, refreshing cut fruits.',
    },
    coke: { name: 'Coca-Cola', desc: '' },
    'coke-zero': { name: 'Coke Zero', desc: '' },
    fanta: { name: 'Fanta', desc: '' },
    sprite: { name: 'Sprite', desc: '' },
    'red-bull': { name: 'Red Bull', desc: '' },
    heineken: { name: 'Heineken', desc: '' },
    corona: { name: 'Corona', desc: '' },
    soda: { name: 'Soda', desc: '' },
    water: { name: 'Mineral Water', desc: '' },
    'orange-juice': { name: 'Freshly Squeezed Orange Juice', desc: '' },
    'fruit-shake': {
      name: 'Refreshing Fruit Shake',
      desc: 'Non-alcoholic. Water / orange / soy base (depending on available fruits).',
    },
    limonana: {
      name: 'Large Limonana',
      desc: 'Regular €10 · with alcohol €15',
    },
    'keter-david': {
      name: 'Keter David',
      desc: 'Vodka, strawberries and fresh kiwi, balanced with a touch of lemon. A fruity, refreshing and elegant cocktail with a gentle acidity.',
    },
    'gan-eden': {
      name: 'Gan Eden',
      desc: 'Tequila, fresh watermelon and melon with fresh mint. A light, refreshing and fruity cocktail with a distinctly summery taste.',
    },
    'eretz-zavat': {
      name: 'Eretz Zavat Ananas U\'Dvash',
      desc: 'Vodka, pineapple and fresh nectarine. A rich tropical mix, sweet and balanced with fruity freshness.',
    },
    'kerem-yisrael': {
      name: 'Kerem Yisrael',
      desc: 'Jameson, apple and fresh grapes. A deep, balanced cocktail combining natural sweetness with a gentle acidity and the aroma of fresh fruit.',
    },
    'vodka-redbull': { name: 'Vodka Red Bull', desc: '' },
    'shake-base-soy': { name: 'Soy', desc: '' },
    'shake-base-water': { name: 'Water', desc: '' },
    'shake-base-orange': { name: 'Orange', desc: '' },
    'limonana-alcohol-yes': { name: 'Yes', desc: '' },
    'limonana-alcohol-no': { name: 'No', desc: '' },
    espresso: {
      name: 'Espresso',
      desc: '',
    },
    hafukh: {
      name: 'Hafukh (soy milk available)',
      desc: '',
    },
    'black-coffee': { name: 'Black Coffee', desc: '' },
    'mint-tea': { name: 'Hot Mint Tea', desc: '' },
    puree: { name: 'Mashed Potatoes', desc: '' },
    rice: { name: 'White Rice', desc: '' },
    'green-beans': { name: 'Green Beans', desc: '' },
    'fries-side': { name: 'Crispy Fries', desc: '' },
    'starter-rice': { name: 'White Rice', desc: '' },
    'starter-green-beans': { name: 'Green Beans', desc: '' },
    'starter-puree': { name: 'Mashed Potatoes', desc: '' },
  },
};

function dishImage(id) {
  return `assets/images/dishes/${id}.webp`;
}

/** Butcher-shop photos live in assets/images/bif/ */
function bifImage(filename) {
  return `assets/images/bif/${encodeURIComponent(filename)}`;
}

const MENU_DATA = {
  restaurant: 'לחיים בכריתים',
  categories: [
    {
      id: 'starters',
      titleKey: 'categories.starters',
      items: [
        {
          id: 'salad-plate',
          name: 'פלטת סלטים פתיחה',
          printName: 'Paletet Salatim',
          description: 'מבחר סלטי הבית המרעננים לצד לחם חם (מומלץ למרכז שולחן).',
          price: 15,
          image: dishImage('salad-plate'),
        },
        {
          id: 'hatzil-patuach',
          name: 'חציל פתוח למרכז שולחן',
          printName: 'Hatzil',
          description: 'חציל בלאדי פתוח עם טחינה מעל וכוסברה.',
          price: 15,
          image: dishImage('hatzil-patuach'),
          dineInOnly: true,
        },
        {
          id: 'hummus',
          name: 'חומוס הבית',
          printName: 'Hummus',
          description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ולחם.',
          price: 15,
          image: dishImage('hummus'),
        },
        {
          id: 'hummus-egg',
          name: 'חומוס עם ביצה',
          printName: 'Hummus Im Beitza',
          description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ולחם בתוספת ביצה.',
          price: 17,
          image: dishImage('hummus-egg'),
        },
        {
          id: 'hummus-meat',
          name: 'חומוס בשר',
          printName: 'Hummus Basar',
          description: 'חומוס קרמי בעבודת יד, מוגש עם שמן זית, כמון ולחם בתוספת בשר.',
          price: 19,
          image: dishImage('hummus-meat'),
        },
        {
          id: 'mushrooms',
          name: 'פטריות חמות',
          printName: 'Pitriyot Hamot',
          description: 'פטריות טריות מוקפצות בשום, שמן זית ופטרוזיליה.',
          price: 10,
          image: dishImage('mushrooms'),
        },
        {
          id: 'fries-classic',
          name: "צ'יפס קלאסי",
          printName: 'Chips',
          description: 'מנת תפוחי אדמה פריכים.',
          price: 10,
          image: dishImage('fries'),
        },
        {
          id: 'starter-rice',
          name: 'אורז לבן',
          printName: 'Orez Lavan',
          description: '',
          price: 9,
          image: dishImage('white-rice'),
        },
        {
          id: 'starter-green-beans',
          name: 'שעועית ירוקה',
          printName: 'Shayouit Yeruka',
          description: '',
          price: 9,
          image: dishImage('green-beans'),
        },
        {
          id: 'starter-puree',
          name: 'פירה',
          printName: 'Pire',
          description: '',
          price: 9,
          image: dishImage('puree'),
        },
        {
          id: 'bread',
          name: 'לחם',
          printName: 'Lechem',
          description: '',
          price: 2,
          image: dishImage('lechem'),
        },
      ],
    },
    {
      id: 'specials',
      titleKey: 'categories.specials',
      items: [
        {
          id: 'staik-antarkot',
          name: 'סטייק אנטריקוט פרימיום',
          printName: 'Entrecote',
          description: 'סטייק אנטריקוט פרימיום 300 גרם, צלוי למידת עשייה מדיום, מוגש עם ירקות על האש, צ\'ימיצ\'ורי וקרם בטטה.',
          price: 52,
          image: dishImage('staik-antarkot'),
        },
        {
          id: 'asado',
          name: 'אסאדו מתפרק מהעצם',
          printName: 'Asado',
          description: 'אסאדו בבישול ארוך, במשקל 600–700 גרם, עד שהבשר רך ומתפרק מהעצם, מוגש עם ירקות על האש, צ\'ימיצ\'ורי וקרם בטטה.',
          price: 78,
          image: dishImage('asado'),
        },
      ],
    },
    {
      id: 'mains',
      titleKey: 'categories.mains',
      descriptionKey: 'mainsNote',
      sidesTitleKey: 'mainsSidesTitle',
      sidesListKey: 'mainsSidesList',
      items: [
        {
          id: 'schnitzel',
          name: 'שניצל של השף',
          printName: 'Shnitzel',
          description: 'חזה עוף פריך בציפוי פירורי לחם מוזהבים.',
          price: 25,
          image: dishImage('schnitzel'),
        },
        {
          id: 'chicken-steak',
          name: 'סטייק פרגית בגריל',
          printName: 'Pargit',
          description: 'נתח פרגית עסיסי בתיבול ים־תיכוני.',
          price: 26,
          image: dishImage('chicken-steak'),
        },
        {
          id: 'whole-fish',
          name: 'דג שלם בתנור',
          printName: 'Dag Shalem',
          description: 'דניס טרי אפוי עם עשבי תיבול ושמן זית.',
          price: 29,
          image: dishImage('denis'),
        },
        {
          id: 'denis-fillet',
          name: 'פילה דניס בתנור',
          printName: 'File Denis',
          description: 'פילה דניס בתנור בעשבי תיבול ירוקים ושמן זית.',
          price: 29,
          image: dishImage('denis-fillet'),
        },
        {
          id: 'salmon',
          name: 'נתח סלמון בתנור',
          printName: 'Salmon',
          description: 'פילה סלמון אפוי בתיבול עדין.',
          price: 29,
          image: dishImage('salmon'),
        },
        {
          id: 'kebab',
          name: 'שיפודי קבב',
          printName: 'Shpudei Kabab',
          description: 'מוגש לצד טחינה וסלטון קטן.',
          price: 27,
          image: dishImage('kebab'),
        },
        {
          id: 'chicken-stirfry',
          name: 'מוקפץ עוף',
          printName: 'Mukpatz Of',
          description: 'נתחי עוף מוקפצים עם ירקות ברוטב סויה וג\'ינג\'ר.',
          price: 20,
          image: dishImage('chicken-stirfry'),
        },
        {
          id: 'hamburger-fries',
          name: 'המבורגר וצ\'יפס',
          printName: 'Hamburger Chips',
          description: 'קציצת המבורגר בלחמנייה עם עגבנייה חסה ורטבים בצד כולל צ\'יפס ושתייה לבחירה',
          price: 25,
          image: 'assets/images/dishes/amburger.webp',
        },
      ],
    },
    {
      id: 'salads',
      titleKey: 'categories.salads',
      items: [
        {
          id: 'chicken-salad',
          name: 'סלט פרגית',
          printName: 'Salat Pargit',
          description: 'נתחי פרגית על סלט ירקות טרי.',
          price: 18,
          image: dishImage('chicken-salad'),
        },
        {
          id: 'israeli-salad',
          name: 'סלט ישראלי',
          printName: 'Salat Israeli',
          description: 'סלט ירקות טרי.',
          price: 10,
          image: dishImage('israeli-salad'),
        },
        {
          id: 'green-salad',
          name: 'סלט ירוק',
          printName: 'Salat Yarok',
          description: 'מבחר עלים טריים עם רוטב ויניגרט.',
          price: 9,
          image: dishImage('green-salad'),
        },
        {
          id: 'market-salad',
          name: 'סלט שוק',
          printName: 'Salat Shuk',
          description: 'ירקות העונה טריים.',
          price: 9,
          image: dishImage('market-salad'),
        },
      ],
    },
    {
      id: 'cocktails',
      titleKey: 'categories.cocktails',
      items: [
        {
          id: 'orange-juice',
          name: 'מיץ תפוזים סחוט טבעי',
          printName: 'Mitz Tapuzim',
          description: '',
          price: 7,
          image: dishImage('orange-juice'),
          nonAlcoholic: true,
        },
        {
          id: 'fruit-shake',
          name: 'שייק פירות מרענן',
          printName: 'Shake Perot',
          description: 'בלי אלכוהול. על בסיס מים / תפוזים / סויה (בהתאם לפירות הזמינים).',
          price: 10,
          image: dishImage('fruit-shake'),
          nonAlcoholic: true,
        },
        {
          id: 'limonana',
          name: 'לימונענע גרוס',
          printName: 'Limonana Gros',
          description: 'רגיל €10 · עם אלכוהול €15',
          price: 10,
          image: dishImage('limonana'),
        },
        {
          id: 'keter-david',
          name: 'כתר דוד',
          printName: 'Keter David',
          description: 'וודקה, תותים וקיווי טרי, מאוזנים בנגיעת לימון. קוקטייל פירותי, רענן ואלגנטי עם חמיצות עדינה.',
          price: 14,
          image: dishImage('keter-david'),
        },
        {
          id: 'gan-eden',
          name: 'גן עדן',
          printName: 'Gan Eden',
          description: 'טקילה, אבטיח ומלון טריים עם נענע טרייה. קוקטייל קליל, מרענן ופירותי עם טעם קיצי במיוחד.',
          price: 14,
          image: dishImage('gan-eden'),
        },
        {
          id: 'eretz-zavat',
          name: 'ארץ זבת אננס ודבש',
          printName: 'Eretz Zavat',
          description: 'וודקה, אננס ונקטרינה טרייה. שילוב טרופי עשיר, מתוק ומאוזן עם רעננות פירותית.',
          price: 15,
          image: dishImage('eretz-zavat'),
        },
        {
          id: 'kerem-yisrael',
          name: 'כרם ישראל',
          printName: 'Kerem Yisrael',
          description: 'ג\'יימסון, תפוח וענבים טריים. קוקטייל עמוק ומאוזן, המשלב מתיקות טבעית עם חמיצות עדינה וניחוח של פירות טריים.',
          price: 15,
          image: dishImage('kerem-israel'),
        },
        {
          id: 'vodka-redbull',
          name: 'וודקה רדבול',
          printName: 'Vodka Redbull',
          description: '',
          price: 9,
          image: dishImage('vodka-redbull'),
        },
      ],
    },
    {
      id: 'coldDrinks',
      titleKey: 'categories.coldDrinks',
      items: [
        { id: 'coke', name: 'קוקה קולה', printName: 'Coca Cola', description: '', price: 3, image: dishImage('coke') },
        { id: 'coke-zero', name: 'קולה זירו', printName: 'Cola Zero', description: '', price: 3, image: dishImage('coke-zero') },
        { id: 'fanta', name: 'פאנטה', printName: 'Fanta', description: '', price: 3, image: dishImage('fanta') },
        { id: 'sprite', name: 'ספרייט', printName: 'Sprite', description: '', price: 3, image: dishImage('sprite') },
        { id: 'red-bull', name: 'רד בול', printName: 'Red Bull', description: '', price: 3, image: dishImage('red-bull') },
        { id: 'heineken', name: 'בירה הייניקן', printName: 'Bira Heineken', description: '', price: 4, image: dishImage('heineken') },
        { id: 'corona', name: 'בירה קורונה', printName: 'Bira Corona', description: '', price: 4, image: dishImage('corona') },
        { id: 'soda', name: 'סודה', printName: 'Soda', description: '', price: 3, image: dishImage('soda') },
        { id: 'water', name: 'מים מינרליים', printName: 'Mayim', description: '', price: 3, image: dishImage('water') },
      ],
    },
    {
      id: 'hotDrinks',
      titleKey: 'categories.hotDrinks',
      items: [
        {
          id: 'espresso',
          name: 'קפה אספרסו',
          printName: 'Cafe Espresso',
          description: '',
          price: 5,
          image: dishImage('espreso'),
        },
        {
          id: 'hafukh',
          name: 'קפה הפוך (אפשרות לחלב סויה)',
          printName: 'Cafe Hafukh',
          description: '',
          price: 5,
          image: dishImage('cappuccino'),
        },
        { id: 'black-coffee', name: 'קפה שחור', printName: 'Cafe Shachor', description: '', price: 5, image: dishImage('black-coffee') },
        { id: 'mint-tea', name: 'תה חם עם נענע', printName: 'Te Im Nana', description: '', price: 5, image: dishImage('mint-tea') },
      ],
    },
    {
      id: 'desserts',
      titleKey: 'categories.desserts',
      items: [
        {
          id: 'fruit-plate',
          name: 'פלטת פירות העונה',
          printName: 'Paletet Perot',
          description: 'מבחר פירות טריים, מרעננים וחתוכים.',
          price: 18,
          image: dishImage('fruit-plate'),
        },
      ],
    },
    {
      id: 'butcher',
      titleKey: 'categories.butcher',
      items: [
        {
          id: 'butcher-asado',
          name: 'אסאדו',
          printName: 'Asado',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 31.9,
          pricePerKg: 31.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage('asado.webp'),
        },
        {
          id: 'butcher-entrecote-premium',
          name: 'אנטריקוט',
          printName: 'Entrecote',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 51.9,
          pricePerKg: 51.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage('antrikut.webp'),
        },
        {
          id: 'butcher-goulash',
          name: 'גולש',
          printName: 'Goulash',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 26.9,
          pricePerKg: 26.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage('golsh.webp'),
        },
      ],
    },
    {
      id: 'poultry',
      titleKey: 'categories.poultry',
      items: [
        {
          id: 'butcher-chicken-schnitzel',
          name: 'שניצל עוף',
          printName: 'Chicken Schnitzel',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 19.9,
          pricePerKg: 19.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage('baked-potatoes.webp'),
        },
        {
          id: 'butcher-chicken-leg',
          name: 'כרעי עוף',
          printName: 'Chicken Legs',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 11.9,
          pricePerKg: 11.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage("kar'i'im.webp"),
        },
        {
          id: 'butcher-pargit-skinless',
          name: 'פרגית ללא עור',
          printName: 'Skinless Pargit',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 19.9,
          pricePerKg: 19.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage('pirgit.webp'),
        },
        {
          id: 'butcher-wings-drumettes',
          name: 'כנפיים',
          printName: 'Wings',
          description: 'כשר למהדרין -\nשחיטת ליובאוויטש',
          price: 7.9,
          pricePerKg: 7.9,
          soldByPack: true,
          unitType: 'pack',
          image: bifImage("knafi'im.webp"),
        },
      ],
    },
  ],
};

const HOT_SIDE_ITEMS = [
  { id: 'fries-side', name: "צ'יפס פריך", printName: 'Chips', description: '', price: 0, image: dishImage('fries') },
  { id: 'rice', name: 'אורז לבן', printName: 'Orez Lavan', description: '', price: 0, image: dishImage('white-rice') },
  { id: 'green-beans', name: 'שעועית ירוקה', printName: 'Shayouit Yeruka', description: '', price: 0, image: dishImage('green-beans') },
  { id: 'puree', name: 'פירה', printName: 'Pire', description: '', price: 0, image: dishImage('puree') },
];

/** Fruit-shake base choices (same picker UX as hot sides). */
const SHAKE_BASE_ITEMS = [
  { id: 'shake-base-soy', name: 'סויה', printName: 'Soya', description: '', price: 0, image: '' },
  { id: 'shake-base-water', name: 'מים', printName: 'Mayim', description: '', price: 0, image: '' },
  { id: 'shake-base-orange', name: 'תפוזים', printName: 'Tapuzim', description: '', price: 0, image: '' },
];

const MAIN_COURSE_IDS = new Set(['schnitzel', 'chicken-steak', 'whole-fish', 'denis-fillet', 'salmon']);
const HOT_SIDE_IDS = new Set(['fries-side', 'rice', 'green-beans', 'puree']);
const SHAKE_BASE_IDS = new Set(['shake-base-soy', 'shake-base-water', 'shake-base-orange']);
const FRUIT_SHAKE_ID = 'fruit-shake';
const LIMONANA_ID = 'limonana';
/** Alcohol yes/no for Limonana Gros — picker only, prints as + Yes / + No. */
const LIMONANA_ALCOHOL_ITEMS = [
  { id: 'limonana-alcohol-yes', name: 'כן', printName: 'Yes', description: '', price: 5, image: '' },
  { id: 'limonana-alcohol-no', name: 'לא', printName: 'No', description: '', price: 0, image: '' },
];
const LIMONANA_ALCOHOL_IDS = new Set(['limonana-alcohol-yes', 'limonana-alcohol-no']);
const HAMBURGER_MEAL_ID = 'hamburger-fries';
/** Soft drinks only with hamburger meal (no beer, coffee, tea, limonana, or fruit-shake). */
const HAMBURGER_DRINK_IDS = new Set([
  'coke', 'coke-zero', 'fanta', 'sprite', 'red-bull', 'soda', 'water',
]);
const MAX_SIDES_PER_MAIN = 1;
const BUTCHER_PACK_WEIGHT_MIN_KG = 0.98;
const BUTCHER_PACK_WEIGHT_MAX_KG = 1.2;
const BUTCHER_DEFAULT_DELIVERY_FEE = 10;
const TAKEAWAY_DEFAULT_DELIVERY_FEE = 10;
const TAKEAWAY_DELIVERY_MIN_ORDER = 75;

const SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/lechim_crete/',
  facebook: 'https://www.facebook.com/share/19Pwg3YuSb/?mibextid=wwXIfr',
};

window.MENU_DATA = MENU_DATA;
window.HOT_SIDE_ITEMS = HOT_SIDE_ITEMS;
window.SHAKE_BASE_ITEMS = SHAKE_BASE_ITEMS;
window.LIMONANA_ALCOHOL_ITEMS = LIMONANA_ALCOHOL_ITEMS;
window.TRANSLATIONS = TRANSLATIONS;
window.DISH_I18N = DISH_I18N;
window.MAIN_COURSE_IDS = MAIN_COURSE_IDS;
window.HOT_SIDE_IDS = HOT_SIDE_IDS;
window.SHAKE_BASE_IDS = SHAKE_BASE_IDS;
window.FRUIT_SHAKE_ID = FRUIT_SHAKE_ID;
window.LIMONANA_ID = LIMONANA_ID;
window.LIMONANA_ALCOHOL_IDS = LIMONANA_ALCOHOL_IDS;
window.HAMBURGER_MEAL_ID = HAMBURGER_MEAL_ID;
window.HAMBURGER_DRINK_IDS = HAMBURGER_DRINK_IDS;
window.MAX_SIDES_PER_MAIN = MAX_SIDES_PER_MAIN;
window.BUTCHER_PACK_WEIGHT_MIN_KG = BUTCHER_PACK_WEIGHT_MIN_KG;
window.BUTCHER_PACK_WEIGHT_MAX_KG = BUTCHER_PACK_WEIGHT_MAX_KG;
window.BUTCHER_DEFAULT_DELIVERY_FEE = BUTCHER_DEFAULT_DELIVERY_FEE;
window.TAKEAWAY_DEFAULT_DELIVERY_FEE = TAKEAWAY_DEFAULT_DELIVERY_FEE;
window.TAKEAWAY_DELIVERY_MIN_ORDER = TAKEAWAY_DELIVERY_MIN_ORDER;
window.SOCIAL_LINKS = SOCIAL_LINKS;

